# Generated by Django 2.2.6 on 2019-10-16 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login2',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='last login 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$150000$gUNIu38nLVCA$DK9w93ynxRArAiBrIpgOoH6eJz2M1eSdP7rSyDoVkCo=', max_length=128, verbose_name='password'),
        ),
    ]
