# Generated by Django 3.0 on 2020-02-01 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_auto_20191222_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='usersessionlog',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$826xPF5NV65T$Crp4iQJHIe8SdRL1oM8xdx6qJM2u6eub1SAxs/mBtD0=', max_length=128, verbose_name='password'),
        ),
    ]
