# Generated by Django 3.0.2 on 2020-02-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_auto_20200202_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$ZwdYBX8j0idH$E3Zk5ngIkoG7v55Wxhg4gxWxCTvCULJVis/6w3EqKfg=', max_length=128, verbose_name='password'),
        ),
    ]
