# Generated by Django 3.0.3 on 2020-03-15 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_auto_20200202_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$3tpReOOn4T0L$084AToIsFiNQiDbWu4MqiDDLkUFfKFKobwPjTikLWA0=', max_length=128, verbose_name='password'),
        ),
    ]
