# Generated by Django 3.0.3 on 2020-04-02 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_auto_20200315_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersessionlog',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$iYId0uLn5tJA$PhxY2PzoxzhlHydS0kPhVRWGN1RN0arOj70eyP84Vnc=', max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usersessionlog',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
